ezpublish:
    system:
        default:
            image_variations:
                gallery_image:
                    reference: ~
                    filters:
                        - { name: geometry/scalewidth, params: [1080] }
                gallery_image_thumb:
                    reference: ~
                    filters:
                        - { name: geometry/scalewidth, params: [320] }
                news_image:
                    reference: ~
                    filters:
                        - { name: geometry/scaledownonly, params: [540, 380] }
                profil_image:
                    reference: ~
                    filters:
                        - { name: geometry/scaledownonly, params: [600, 600] }
                top_image:
                    reference: ~
                    filters:
                        - { name: geometry/scaledownonly, params: [1080, 1080] }
                banner_image:
                    reference: ~
                    filters:
                        - { name: geometry/scaledownonly, params: [1920, 400] }
                banner_image_mobile:
                    reference: ~
                    filters:
                        - { name: geometry/scalewidth, params: [450] }