services:
    app.core_helper:
             class: %site_authors.core_helper.class%
             arguments: [@ezpublish.api.repository, @service_container, @ezpublish_legacy.kernel, @ezpublish.siteaccess]
